version: "3.9"

services:
  user_app:
    container_name: user_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - ./.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
